In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
QCL_df = pd.read_csv('data/faostat/QCL_clean.csv')

In [3]:
QCL_df.rename(columns={'Area':'Country','Value':'Hectare'},inplace=True)
QCL_df.drop(columns=['Unit'],inplace=True)

In [4]:
QCL_df.dtypes

Country    object
Item       object
Year        int64
Hectare     int64
dtype: object

In [5]:
QCL_df.Item.unique()

array(['Rice', 'Cattle and Buffaloes', 'Soya beans', 'Cocoa beans',
       'Coffee, green', 'Oil palm fruit', 'Green corn/Maize'],
      dtype=object)

In [6]:
QCLdict = {'Rice': QCL_df.loc[QCL_df.Item=='Rice'],
           'Soy': QCL_df.loc[QCL_df.Item=='Soya beans'],
           'Corn': QCL_df.loc[QCL_df.Item=='Green corn/Maize'],
           'Palm Oil': QCL_df.loc[QCL_df.Item=='Oil palm fruit'],
           'Coffee': QCL_df.loc[QCL_df.Item=='Coffee, green'],
           'Cocoa': QCL_df.loc[QCL_df.Item=='Cocoa beans'],
           'Cattle/Buffalo':QCL_df.loc[QCL_df.Item=='Cattle and Buffaloes']}

In [7]:
for df in QCLdict.values(): 
    df=df[['Country','Year','Hectare']]
QCLdict['Cattle/Buffalo'] = QCLdict['Cattle/Buffalo'].rename(columns={'Hectare':'Animal'})

In [8]:
for df in QCLdict.values(): display(df.Country.nunique())

145

116

181

44

84

63

196

In [9]:
dict = {}

In [10]:
for df in QCLdict.values():
    for name in df.Country.unique():
        df.loc[df.Country==name]

In [11]:
QCL_country = QCL_df.groupby('Country').agg(list)

In [12]:
QCLdictC = {}

In [47]:
for name in QCL_country.index:
    dfx = pd.DataFrame([*QCL_country.loc[name]], index=['Name','Year','Value']).T
    dfx = dfx.groupby('Name').agg(list)
    items=[]
    for n in dfx.index:
        items.append({'item':n,'years':[*dfx.Year[n]],'values':[*dfx.Value[n]]})
    QCLdictC[name] = items

In [49]:
QCLdictC['Indonesia']

[{'product': 'Cattle and Buffaloes',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [9249281,
   9387000,
   9374000,
   9373000,
   9767000,
   9609000,
   9313000,
   10805000,
   9387000,
   9022000,
   9163000,
   9108000,
   8665000,
   8795000,
   8674000,
   8521000,
   8509000,
   8642000,
   8794000,
   8897000,
   9004000,
   9107000,
   11292000,
   11979000,
   12563000,
   12928000,
   12805712,
   12970000,
   13318800,
   13745286,
   13977682,
   14553000,
   13885710,
   14472120,
   14670000,
   14986791,
   15003388,
   14463167,
   13779491,
   13413277,
   13471129,
   13700590,
   12963534,
   12936187,
   12697491,
   13041731,
   13600650,
   14187320,
   14692765,
   15581174,
   16129451,
   17418991,
   13795875,
   16062022,
   16766635,
   17359221,
   17751006,
   17327223,
   18063840,
   18594619,
   19120403,
   19780357]},
 {'product': 'Cocoa beans',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [6690,
   7375,
   6659,
   7662,
   8431,
   7783,
   9176,
   9470,
   10041,
   8107,
   9163,
   10607,
   8044,
   8648,
   7376,
   8800,
   11208,
   12553,
   16000,
   19355,
   22500,
   23000,
   29000,
   43076,
   33824,
   50632,
   61676,
   107566,
   135020,
   158820,
   183956,
   189596,
   299546,
   359086,
   374261,
   398655,
   386605,
   403166,
   667897,
   749917,
   765405,
   776901,
   961107,
   1090960,
   1167046,
   905730,
   923968,
   1425216,
   1587136,
   1651539,
   1732600,
   1852900,
   1740600,
   1727400,
   1709284,
   1701351,
   1658421,
   1611014,
   1560945,
   1508955,
   1460396,
   1442403]},
 {'product': 'Coffee, green',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [182000,
   189000,
   246000,
   209000,
   238000,
   250000,
   282000,
   278000,
   267000,
   305000,
   321000,
   319000,
   266000,
   262000,
   309000,
   341000,
   380327,
   391173,
   443914,
   498013,
   527046,
   515778,
   539000,
   539000,
   613000,
   655182,
   652518,
   716656,
   724063,
   746759,
   760308,
   793000,
   810000,
   797000,
   846078,
   836621,
   831782,
   844172,
   900000,
   1260687,
   1313383,
   1372184,
   1381730,
   1303943,
   1255272,
   1308732,
   1295912,
   1295111,
   1266235,
   1268476,
   1293000,
   1233900,
   1241700,
   1230500,
   1230001,
   1228512,
   1238598,
   1252826,
   1245359,
   1250452,
   1279570,
   1285778]},
 {'product': 'Green corn/Maize',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [2562000,
   3280000,
   2669000,
   3761000,
   2627000,
   3903000,
   2677000,
   3359010,
   2576820,
   3083610,
   2775700,
   2312050,
   3589170,
   2826870,
   2607870,
   2170050,
   2646510,
   3083610,
   2666121,
   2814940,
   3023039,
   2131299,
   3073227,
   3126246,
   2481966,
   3184759,
   2681033,
   3482751,
   3021199,
   3235592,
   2985100,
   3704346,
   3013534,
   3200400,
   3742838,
   3836570,
   3439224,
   3929820,
   3542357,
   3587000,
   3367900,
   3204830,
   3442511,
   3440914,
   3716987,
   3429805,
   3721324,
   4103413,
   4264659,
   4234976,
   3961192,
   4056515,
   3917004,
   3933019,
   3882067,
   4555469,
   5668169,
   5812694,
   3732274,
   3126967,
   3086356,
   4210473]},
 {'product': 'Oil palm fruit',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [70000,
   70000,
   75000,
   80000,
   80000,
   85000,
   85000,
   90000,
   90000,
   100000,
   95000,
   100000,
   100000,
   110000,
   142000,
   130000,
   140000,
   180000,
   200000,
   204000,
   230000,
   239700,
   255300,
   296300,
   348700,
   374100,
   421600,
   535000,
   590000,
   673033,
   772245,
   875100,
   921000,
   1045000,
   1190000,
   1428350,
   1622503,
   1795081,
   1847000,
   2014000,
   2200000,
   2790000,
   3040000,
   3320000,
   3690000,
   4110000,
   4560000,
   4980000,
   5370000,
   8385394,
   8992824,
   9572715,
   10465020,
   10465020,
   10754801,
   11201465,
   14048722,
   14326350,
   14456612,
   14586597,
   14621693,
   14953126]},
 {'product': 'Rice',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [6857000,
   7283000,
   6731000,
   6980000,
   7327000,
   7691000,
   7516000,
   8020770,
   8013620,
   8135080,
   8324320,
   7897640,
   8403600,
   8508600,
   8495100,
   8368760,
   8359570,
   8929170,
   8803564,
   9005065,
   9381839,
   8988455,
   9162469,
   9763580,
   9902293,
   9988453,
   9922594,
   10138155,
   10531207,
   10502357,
   10281519,
   11103317,
   11012780,
   10733800,
   11438760,
   11569729,
   11140594,
   11730200,
   11963204,
   11793000,
   11500000,
   11521166,
   11477357,
   11922974,
   11839060,
   11786430,
   11748000,
   11728000,
   11778000,
   11797000,
   11653000,
   11591000,
   11631000,
   11473000,
   11389000,
   10600000,
   10900000,
   11377934,
   10677887,
   10657275,
   10411801,
   10452672]},
 {'product': 'Soya beans',
  'years': [1961,
   1962,
   1963,
   1964,
   1965,
   1966,
   1967,
   1968,
   1969,
   1970,
   1971,
   1972,
   1973,
   1974,
   1975,
   1976,
   1977,
   1978,
   1979,
   1980,
   1981,
   1982,
   1983,
   1984,
   1985,
   1986,
   1987,
   1988,
   1989,
   1990,
   1991,
   1992,
   1993,
   1994,
   1995,
   1996,
   1997,
   1998,
   1999,
   2000,
   2001,
   2002,
   2003,
   2004,
   2005,
   2006,
   2007,
   2008,
   2009,
   2010,
   2011,
   2012,
   2013,
   2014,
   2015,
   2016,
   2017,
   2018,
   2019,
   2020,
   2021,
   2022],
  'values': [625000,
   594000,
   539000,
   571000,
   584000,
   605000,
   589000,
   677000,
   553000,
   695000,
   680000,
   698000,
   744000,
   753499,
   752000,
   646336,
   646121,
   733000,
   784489,
   732000,
   810000,
   607788,
   639876,
   859000,
   896220,
   1253767,
   1100565,
   1177400,
   1198096,
   1334100,
   1368199,
   1665000,
   1470210,
   1406920,
   1477432,
   1273290,
   1119079,
   1095070,
   1151079,
   825000,
   678848,
   544522,
   526796,
   565155,
   621541,
   580534,
   459116,
   591899,
   722791,
   660823,
   622254,
   567624,
   550793,
   615685,
   613885,
   576987,
   355799,
   723804,
   301287,
   196417,
   145339,
   202126]}]

In [50]:
gdf = pd.DataFrame({'name': QCLdictC.keys(), 'items':QCLdictC.values()})
gdf

,name,items
0,Afghanistan,"[{'product': 'Cattle and Buffaloes', 'years': ..."
1,Albania,"[{'product': 'Cattle and Buffaloes', 'years': ..."
2,Algeria,"[{'product': 'Cattle and Buffaloes', 'years': ..."
3,Angola,"[{'product': 'Cattle and Buffaloes', 'years': ..."
4,Antigua and Barbuda,"[{'product': 'Cattle and Buffaloes', 'years': ..."
...,...,...
193,Venezuela (Bolivarian Republic of),"[{'product': 'Cattle and Buffaloes', 'years': ..."
194,Viet Nam,"[{'product': 'Cattle and Buffaloes', 'years': ..."
195,Yemen,"[{'product': 'Cattle and Buffaloes', 'years': ..."
196,Zambia,"[{'product': 'Cattle and Buffaloes', 'years': ..."
197,Zimbabwe,"[{'product': 'Cattle and Buffaloes', 'years': ..."

In [51]:
gdf.to_json('data/faostat/qcl.json')